# Generated by Django 4.1 on 2023-04-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodAlumno', models.CharField(max_length=100)),
                ('avance', models.IntegerField()),
            ],
        ),
    ]
